// icons are stored locally in assets/icons, so the readme does not depend on hotlinked images
// sources: devicon (cdn.jsdelivr.net/gh/devicons/devicon), simple-icons (cdn.simpleicons.org),
// primer octicons (@primer/octicons) and lobehub icons (@lobehub/icons-static-svg);
// monochrome icons are recolored to #8b949e so they are visible in both light and dark themes
export const icon = (kind, key) => `<img src="assets/icons/${icons[kind]?.[key] || "fallback"}.svg" width="24" height="24" alt="${key}" title="${key}" />`;

export const icons = {
  languages: {
    Other: "other",
    Text: "text",
    Diff: "diff",
    Markdown: "markdown",
    TypeScript: "typescript",
    TSConfig: "typescript",
    TSX: "react",
    JavaScript: "javascript",
    JSX: "react",
    Ruby: "ruby",
    ERB: "rails",
    Bash: "bash",
    Shell: "bash",
    PowerShell: "powershell",
    Batchfile: "terminal",
    Python: "python",
    "Jupyter Notebook": "jupyter",
    Jinja: "jinja",
    HTML: "html",
    CSS: "css",
    SCSS: "sass",
    Sass: "sass",
    Vue: "vue",
    Handlebars: "handlebars",
    CoffeeScript: "coffeescript",
    Swift: "swift",
    JSON: "json",
    YAML: "yaml",
    TOML: "toml",
    INI: "settings",
    XML: "xml",
    SQL: "database",
    "C#": "csharp",
    Razor: "dotnet",
    ASP: "dotnet",
    Docker: "docker",
    Dockerfile: "docker",
    PHP: "php",
    Go: "go",
    Java: "java",
    Kotlin: "kotlin",
    Groovy: "groovy",
    Haskell: "haskell",
    Rust: "rust",
    C: "c",
    "C++": "cplusplus",
    Lua: "lua",
    GraphQL: "graphql",
    Git: "git",
    "Git Config": "git",
    Terraform: "terraform",
    HCL: "terraform",
    Makefile: "gnu",
    "Vim Script": "vim",
    Mermaid: "mermaid",
    AutoHotkey: "autohotkey",
    Groff: "manual",
    Roff: "manual",
  },
  editors: {
    "Claude Code": "claude",
    "Codex Vscode": "codex",
    "Codex Exec": "codex",
    "Opencode Cli": "opencode",
    "Copilot CLI": "copilot",
    Cursor: "cursor",
    "VS Code": "vscode",
    Zed: "zed",
    Xcode: "xcode",
    "Android Studio": "androidstudio",
    WebStorm: "webstorm",
    IntelliJ: "intellij",
    Rider: "rider",
    PyCharm: "pycharm",
    Ghostty: "ghostty",
    iTerm2: "iterm2",
    Terminal: "terminal",
    Chrome: "chrome",
    Browser: "chrome",
    Safari: "safari",
    Slack: "slack",
    Music: "applemusic",
    Notes: "note",
  },
  platforms: {
    Mac: "apple",
    Windows: "windows",
    Linux: "linux",
  },
};
